{{- if .Values.ingress.enabled -}}
{{- $fullName := include "k8s-workshop.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "k8s-workshop.fullname" . }}
  labels:
    app: {{ template "k8s-workshop.fullname" . }}
    chart: {{ template "k8s-workshop.chart" . }}
    release: {{ .Release.Name }}
    environment: {{ .Values.environment }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
        - path: {{ $ingressPath }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: http
  {{- end }}
{{- end }}