name: nginx-ingress
  
controller:
  publishService:
    enabled: true

  # TODO: Flip after HPA is deployed
  autoscaling:
    enabled: false
  #  minReplicas: 1
  #  maxReplicas: 11
  #  targetCPUUtilizationPercentage: 50

  service:
    targetPorts:
      http: http
      https: http
    annotations: 
      dns.alpha.kubernetes.io/external: "www.k8sworkshop.com,*.k8sworkshop.com,*.staging.k8sworkshop.com"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: |-
        arn:aws:acm:us-east-1:739084615478:certificate/bee506b1-1ace-4032-bb53-5b989ca64894
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Team=k8s-on-aws-workshop"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    externalTrafficPolicy: "Local"
    type: LoadBalancer

  # TODO: Flip after prom is deployed
  stats:
    enabled: false

  # TODO: Flip after prom is deployed
  metrics:
    enabled: false

defaultBackend:
  enabled: true
  name: default-backend
  image:
    repository: k8s.gcr.io/defaultbackend
    tag: "1.3"
    pullPolicy: IfNotPresent

rbac:
  create: true